### PR TITLE
Add support for arbitrary leading dimensions

### PR DESCRIPTION
**Pull request by LysanderdeJong**
Should allow it to work better with sampling more slices or working with 3D MRI data.

### CODE REVIEW

**Review by wdika — CHANGES_REQUESTED** [review]
Thanks @LysanderdeJong! The test for the Gaussian1D masking is falling, can you please fix the dimensions there? Also, please add this option to random1D and equidistant1D masking, to make it reproducible for all masks.

Finally, make sure [test_subsample](https://github.com/wdika/mridc/blob/main/tests/collections/reconstruction/test_subsample.py) is passing.

**Comment by LysanderdeJong** [comment]
Sure I'll have a look.

**Comment by LysanderdeJong** [comment]
From my testing random1D and equidistant1D already support arbitrary leading dimensions.
Gaussian1D test checks for a mask size which has less dimensions then the number of dimensions in the input shape. Is this correct?

**Comment by wdika** [comment]
> From my testing random1D and equidistant1D already support arbitrary leading dimensions. Gaussian1D test checks for a mask size which has less dimensions then the number of dimensions in the input shape. Is this correct?

For the 1D case the height dim is also 1. For example,
- 2D mask -> [1, 1, height, width, 1]
- 1D mask -> [1, 1, 1, width, 1]

**Comment by LysanderdeJong** [comment]
> For the 1D case the height dim is also 1. For example,
> 
> * 2D mask -> [1, 1, height, width, 1]
> * 1D mask -> [1, 1, 1, width, 1]

Then I think the way the shapes are checked for in the tests do not check for correctly.

**Comment by wdika** [comment]
> > For the 1D case the height dim is also 1. For example,
> > 
> > * 2D mask -> [1, 1, height, width, 1]
> > * 1D mask -> [1, 1, 1, width, 1]
> 
> Then I think the way the shapes are checked for in the tests do not check for correctly.

It should be [here](https://github.com/wdika/mridc/blob/dde2475e48e3ad8b2d6430a8a6e03916168c4d4b/tests/collections/reconstruction/test_subsample.py#L127). But I see all checks are passing now. Is it fixed?

**Comment by LysanderdeJong** [comment]
> It should be [here](https://github.com/wdika/mridc/blob/dde2475e48e3ad8b2d6430a8a6e03916168c4d4b/tests/collections/reconstruction/test_subsample.py#L127). But I see all checks are passing now. Is it fixed?

I think it should be fixed.

**Pull request merged**
